os: linux
dist: trusty
language: node_js
node_js: 12
cache: npm
branches:
  only:
    - master
jobs:
  include:
    - stage: tsc
      script: npm run tsc
    - stage: lint
      script: npm run lint
