version: '3'
services:
  app:
    build: .
    environment:
      - TOR_HOST=tor
      - TOR_PORTS=9050,9052,9053,9054
      - WAYPOINTS
      - CRON_EXPRESSION
    volumes:
      - ~/commute-time-collector/logs:/var/log/commute-time-collector
      - ~/commute-time-collector/out:/root/commute-time-collector
  tor:
    image: 'osminogin/tor-simple:latest'
    volumes:
      - ./torrc:/etc/tor/torrc:ro

