version: '3'
services:
  tor:
    image: osminogin/tor-simple:latest
    container_name: tor
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    networks:
      - network
    ports:
      - "127.0.0.1:9050:9050"
      - "127.0.0.1:9052-9054:9052-9054"

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - network
    ports:
      - "4444:4444"

networks:
  network:
    driver: bridge
