version: '3'
services:
  app:
    build: .
    environment:
      - TOR_HOST=tor
      - TOR_PORTS=9050,9052,9053,9054
      - WAYPOINTS
      - CRON_EXPRESSION
    volumes:
      - logs-volume:/var/log/commute-time-collector
      - out-volume:/root/commute-time-collector
  tor:
    image: 'osminogin/tor-simple:latest'
    volumes:
      - ./torrc:/etc/tor/torrc:ro
volumes:
  logs-volume:
  out-volume:
