version: '3'
services:
  tor:
    image: osminogin/tor-simple:latest
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    networks:
      - commute-time-collector-network
    ports:
      - "127.0.0.1:9050:9050"
      - "127.0.0.1:9052-9054:9052-9054"

  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - commute-time-collector-network
    ports:
      - "4444:4444"

networks:
  commute-time-collector-network:
    driver: bridge
