# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run tsc # проверяем, билдится ли тайпскрипт
    - run: npm run lint # прогоняем линтер
    - run: docker build . --file Dockerfile -t okcid/commute-time-collector # проверяем, что не сломали сборку докер контейнера
    - run: docker-compose config -q # проверяем валидность docker-compose
